

services:
  backend:
    build: ./backend 
    ports:
      - "8000:8000"
  
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=review_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_HOST=db
    command: gunicorn review_platform.wsgi:application 
    

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
   
    depends_on:
      - backend
    
  
 

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=review_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    volumes:
      - db_data:/var/lib/postgresql/data  

volumes:
  db_data: