

services:
  backend:
    build: ./backend  # Path to your Django project
    ports:
      - "8000:8000"
  
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=review_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # Change this!
      - POSTGRES_HOST=db
    command: gunicorn review_platform.wsgi:application #For production
    #command: python manage.py runserver 0.0.0.0:8000 # For development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
   
    depends_on:
      - backend
    
  
 

  db:
    image: postgres:14
    ports:
      - "5432:5432" #Only if you want to connect from your machine
    environment:
      - POSTGRES_DB=review_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  # Change this!
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  db_data: